export const REGISTRAR_NUEVO_CLIENTE = 'REGISTRAR_NUEVO_CLIENTE';
export const REGISTRAR_NUEVO_NEGOCIO = 'REGISTRAR_NUEVO_NEGOCIO';
export const INICIAR_REGISTRO = 'INICIAR_REGISTRO';
export const REGISTRO_FAIL = 'REGISTRO_FAIL';

export const CLIENTE_CREAR_CUENTA = 'CLIENTE_CREAR_CUENTA'
export const CLIENTE_FALLO_CREACION_CUENTA = 'CLIENTE_FALLO_CREACION_CUENTA'
export const CLIENTE_INICIAR_CREACION = 'CLIENTE_INICIAR_CREACION'

export const HEADER_BURGUER_HANDLER = 'HEADER_BURGUER_HANDLER';

export const HOME_LOGIN = 'HOME_LOGIN';
export const HOME_JOIN_TO_US = 'HOME_JOIN_TO_US';
export const HOME_JOIN_TO_US_CLOSED = 'HOME_JOIN_TO_US_CLOSED';
export const HOME_WAITING = 'HOME_WAITING';

export const OPEN_ADD_DEL_OPTIONS = 'OPEN_ADD_DEL_OPTIONS';
export const CLOSE_ADD_DEL_OPTIONS = 'CLOSE_ADD_DEL_OPTIONS';

export const ADD_ONE_TO_SELECTED_PRODUCT = 'ADD_ONE_TO_SELECTED_PRODUCT';
export const DEL_ONE_TO_SELECTED_PRODUCT = 'DEL_ONE_TO_SELECTED_PRODUCT';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';

export const EDIT_MODE = 'EDIT_MODE';
export const CLOSE_EDIT_MODE = 'CLOSE_EDIT_MODE';
export const SAVE_CHANGES = 'SAVE_CHANGES';

export const OPEN_EDIT_NEGOCIO = 'OPEN_EDIT_NEGOCIO';
export const CLOSE_EDIT_NEGOCIO = 'CLOSE_EDIT_NEGOCIO';
export const SELECTION_MODAL_BUSINESS = 'SELECTION_MODAL_BUSINESS';
export const SELECTION_MODAL_CUSTOMER = 'SELECTION_MODAL_CUSTOMER';
export const OPEN_EDIT_PRODUCT = 'OPEN_EDIT_PRODUCT';
export const CLOSE_EDIT_PRODUCT = 'CLOSE_EDIT_PRODUCT';

export const ADDED_FOOD_PRODUCT = 'ADDED_FOOD_PRODUCT';
export const CLOSE_ADD_PRODUCT = 'CLOSE_ADD_PRODUCT';

export const BUSINESS_CLICK_ADD_PRODUCT = 'BUSINESS_CLICK_ADD_PRODUCT';