export const REGISTRAR_NUEVO_CLIENTE = 'REGISTRAR_NUEVO_CLIENTE';
export const REGISTRAR_NUEVO_NEGOCIO = 'REGISTRAR_NUEVO_NEGOCIO';
export const INICIAR_REGISTRO = 'INICIAR_REGISTRO';
export const REGISTRO_FAIL = 'REGISTRO_FAIL';
export const REGISTRO_FOTO_ID = 'REGISTRO_FOTO_ID';
export const REGISTRO_FOTO_NEGOCIO = 'REGISTRO_FOTO_NEGOCIO';

export const CLIENTE_CREAR_CUENTA = 'CLIENTE_CREAR_CUENTA'
export const CLIENTE_FALLO_CREACION_CUENTA = 'CLIENTE_FALLO_CREACION_CUENTA'
export const CLIENTE_INICIAR_CREACION = 'CLIENTE_INICIAR_CREACION'

export const HEADER_BURGUER_HANDLER = 'HEADER_BURGUER_HANDLER';

export const HOME_LOGIN = 'HOME_LOGIN';
export const HOME_JOIN_TO_US = 'HOME_JOIN_TO_US';
export const HOME_JOIN_TO_US_CLOSED = 'HOME_JOIN_TO_US_CLOSED';
export const HOME_WAITING = 'HOME_WAITING';
export const HOME_SHOW_MESSAGE = 'HOME_SHOW_MESSAGE';
export const HOME_SET_LOCAL_TOKEN_STORED = 'HOME_SET_LOCAL_TOKEN_STORED';
export const HOME_UPDATE_ALERT = 'HOME_UPDATE_ALERT';
export const HOME_LOGOUT = 'HOME_LOGOUT';


export const OPEN_ADD_DEL_OPTIONS = 'OPEN_ADD_DEL_OPTIONS';
export const CLOSE_ADD_DEL_OPTIONS = 'CLOSE_ADD_DEL_OPTIONS';

export const ADD_ONE_TO_SELECTED_PRODUCT = 'ADD_ONE_TO_SELECTED_PRODUCT';
export const DEL_ONE_TO_SELECTED_PRODUCT = 'DEL_ONE_TO_SELECTED_PRODUCT';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';

export const EDIT_MODE = 'EDIT_MODE';
export const CLOSE_EDIT_MODE = 'CLOSE_EDIT_MODE';
export const SAVE_CHANGES = 'SAVE_CHANGES';

export const OPEN_EDIT_NEGOCIO = 'OPEN_EDIT_NEGOCIO';
export const CLOSE_EDIT_NEGOCIO = 'CLOSE_EDIT_NEGOCIO';
export const SELECTION_MODAL_BUSINESS = 'SELECTION_MODAL_BUSINESS';
export const SELECTION_MODAL_CUSTOMER = 'SELECTION_MODAL_CUSTOMER';
export const OPEN_EDIT_PRODUCT = 'OPEN_EDIT_PRODUCT';
export const CLOSE_EDIT_PRODUCT = 'CLOSE_EDIT_PRODUCT';

export const CLIENTE_MODAL_ORDEN_ABRIR = 'CLIENTE_MODAL_ORDEN_ABRIR';
export const CLIENTE_MODAL_ORDEN_CERRAR = 'CLIENTE_MODAL_ORDEN_CERRAR';
export const CLIENTE_PEDIDO_RECOGER = "CLIENTE_PEDIDO_RECOGER";
export const CLIENTE_PEDIDO_CASA = "CLIENTE_PEDIDO_CASA";
export const CLIENTE_PAGO_EFECTIVO = 'CLIENTE_PAGO_EFECTIVO';
export const CLIENTE_PAGO_TARJETA = 'CLIENTE_PAGO_TARJETA';
export const CLIENTE_REGRESAR_OPCION_PEDIDO = 'CLIENTE_REGRESAR_OPCION_PEDIDO'
export const CLIENTE_PEDIDO_ACEPTAR = 'CLIENTE_PEDIDO_ACEPTAR';
export const CLIENTE_PEDIDO_CANCELAR = 'CLIENTE_PEDIDO_CANCELAR';
export const CLIENTE_REGRESAR_OPCION_PAGO = 'CLIENTE_REGRESAR_OPCION_PAGO'

export const ADDED_FOOD_PRODUCT = 'ADDED_FOOD_PRODUCT';
export const ADD_PRODUCT_SHOW_MESSAGE = 'ADD_PRODUCT_SHOW_MESSAGE';
export const ADD_PRODUCT_UPDATE_ALERT = 'ADD_PRODUCT_UPDATE_ALERT'; 
export const ACCESS_DENY = 'ACCESS_DENY';
export const CHANGE_IS_PRODUCT_ADDED = 'CHANGE_IS_PRODUCT_ADDED';
export const ADD_PRODUCT_INIT_REQUEST = 'ADD_PRODUCT_INIT_REQUEST';

export const BUSINESS_CLICK_ADD_PRODUCT = 'BUSINESS_CLICK_ADD_PRODUCT';

export const ORDERS_BUTTON_SELECTED = 'ORDERS_BUTTON_SELECTED';
export const PREPARE_BUTTON_SELECTED = 'PREPARE_BUTTON_SELECTED';
export const READY_BUTTON_SELECTED = 'READY_BUTTON_SELECTED';

export const CHECKED_RECEIVED_ORDER = 'CHECKED_RECEIVED_ORDER';
export const CHECKED_PREPARING_ORDER = 'CHECKED_PREPARING_ORDER';

export const EMPEZAR_PEDIDO = 'EMPEZAR_PEDIDO';
export const TERMINAR_PEDIDO = 'TERMINAR_PEDIDO';

export const CHECKOUT_INIT = 'CHECKOUT_INIT';
export const CHECKOUT_COMPLETE = 'CHECKOUT_COMPLETE';
export const CHECKOUT_FAIL = 'CHECKOUT_FAIL';

export const GET_PEDIDOS_INIT = 'GET_PEDIDOS_INIT';
export const GET_PEDIDOS_SUCCESS = 'GET_PEDIDOS_SUCCESS';
export const GET_PREPARING_SUCCESS = 'GET_PREPARING_SUCCESS';
export const GET_READY_SUCCESS = 'GET_READY_SUCCESS';
export const GET_PEDIDOS_NEGOCIO_ID_FAIL = 'GET_PEDIDOS_NEGOCIO_ID_FAIL';

export const LOADING_PEDIDOS = 'LOADING_PEDIDOS';
export const CHANGE_STAGE_FAIL = 'CHANGE_STAGE_FAIL';

export const GO_TO_WELCOME = 'GO_TO_WELCOME';
export const GO_TO_PERSONAL = 'GO_TO_PERSONAL';
export const GO_TO_INFO_NEGOCIO = 'GO_TO_INFO_NEGOCIO';
export const GO_TO_NEG_PAGO = 'GO_TO_NEG_PAGO';
export const GO_TO_PRIVACIDAD = 'GO_TO_PRIVACIDAD';

export const REGISTRO_SET_PERSONAL_DATA = 'REGISTRO_SET_PERSONAL_DATA';
export const HANDLE_HORARIO = 'HANDLE_HORARIO';
export const IS_OPEN = 'IS_OPEN';
export const REGISTRO_SET_NEGOCIO_DATA = 'REGISTRO_SET_NEGOCIO_DATA';
export const REGISTRO_PAGO_EFECTIVO = 'REGISTRO_PAGO_EFECTIVO';
export const REGISTRO_PAGO_TARJETA = 'REGISTRO_PAGO_TARJETA';
export const REGISTRO_ENTREGA_DOMICILIO = 'REGISTRO_ENTREGA_DOMICILIO';
export const REGISTRO_ENTREGA_NEGOCIO = 'REGISTRO_ENTREGA_NEGOCIO';

export const CLIENTE_VER_NEGOCIOS = 'CLIENTE_VER_NEGOCIOS';
export const CLIENTE_SET_SELECTED_BUSINESS = 'CLIENTE_SET_SELECTED_BUSINESS'
export const CLIENTE_GET_SELECTED_BUSINESS = 'CLIENTE_GET_SELECTED_BUSINESS'
export const LOAD_NEGOCIO = 'LOAD_NEGOCIO';
export const INIT_GET_NEGOCIO_DETAILS = 'INIT_GET_NEGOCIO_DETAILS';
export const GET_NEGOCIO_DETAILS_SUCCESS = 'GET_NEGOCIO_DETAILS_SUCCESS';
export const GET_NEGOCIO_DETAILS_FAIL = 'GET_NEGOCIO_DETAILS_FAIL';

export const VERIFY_EMAIL_EXIST_INIT = 'VERIFY_EMAIL_EXIST_INIT';
export const VERIFY_EMAIL_EXIST_END = 'VERIFY_EMAIL_EXIST_END';
export const SET_BUSINESS_COORDINATES = 'SET_BUSINESS_COORDINATES';
